---
- name: Post-deploiement OpenRecon
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Attendre que le service démarre
      wait_for:
        port: 8081
        delay: 10
        timeout: 120

    - name: Vérifier l'accès HTTP
      uri:
        url: "http://localhost:8081"
        status_code: 200
